/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package asmeta.transitionrules.turbotransitionrules.validation;

import asmeta.terms.basicterms.Term;

import asmeta.transitionrules.turbotransitionrules.TurboDeclaration;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link asmeta.transitionrules.turbotransitionrules.TurboCallRule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TurboCallRuleValidator {
	boolean validate();

	boolean validateCalledRule(TurboDeclaration value);
	boolean validateParameters(EList<Term> value);
}
